// --- Lista Fixa de Disciplinas ---
export const FIXED_SUBJECTS = [
  'Administração Financeira Orçamentária (AFO)',
  'Administração Geral',
  'Administração Pública',
  'Administração de Materiais',
  'Análise Técnica',
  'Arquivologia',
  'Artes',
  'Astronomia',
  'Atualidades',
  'Auditoria',
  'Biografia',
  'Biologia',
  'Bíblia',
  'Cibersegurança',
  'Ciência de Dados',
  'Ciências Sociais',
  'Conhecimentos Bancários',
  'Conhecimentos Gerais',
  'Contabilidade Geral',
  'Contabilidade Pública',
  'Criminologia',
  'Direito Administrativo',
  'Direito Ambiental',
  'Direito Civil',
  'Direito Constitucional',
  'Direito Digital',
  'Direito Econômico',
  'Direito Educacional',
  'Direito Eleitoral',
  'Direito Empresarial',
  'Direito Financeiro',
  'Direito Internacional',
  'Direito Penal',
  'Direito Previdenciário',
  'Direito Processual Civil',
  'Direito Processual Penal',
  'Direito Processual do Trabalho',
  'Direito Tributário',
  'Direito da Criança e do Adolescente',
  'Direito do Consumidor',
  'Direito do Trabalho',
  'Direitos Humanos',
  'Economia',
  'Educação Física',
  'Engenharia de Software',
  'Espanhol',
  'Estatística',
  'Farmácia',
  'Filosofia',
  'Finanças',
  'Física',
  'Francês',
  'Geografia',
  'Geopolítica',
  'Gestão de Pessoas',
  'Gestão de Projetos',
  'Grego',
  'Hebraico',
  'História',
  'Informática',
  'Inglês',
  'Inteligência Artificial',
  'Investimentos',
  'Japonês',
  'Latim',
  'Legislação Especial',
  'Legislação Específica',
  'Legislação Tributária',
  'Legislação de Trânsito',
  'Libras',
  'Licitações e Contratos',
  'Literatura',
  'Lógica',
  'Marketing',
  'Matemática',
  'Matemática Financeira',
  'Medicina',
  'Medicina Legal',
  'Nutrição',
  'Oratória',
  'Português',
  'Produtividade',
  'Programação',
  'Provas e Simulados',
  'Psicologia',
  'Qconcursos',
  'Química',
  'Redação',
  'Russo',
  'Sociologia',
  'TECconcursos',
  'Teologia',
  'Vendas e Negociação',
  'Xadrez',
  'Ética',
].sort();
